### Environment Variables
@baseUrl =https://stackunderflowbackend.azurewebsites.net
@apiKey =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMSIsIm5iZiI6MTcxODcxOTkzMywiZXhwIjoxNzE4ODA2MzMzLCJpYXQiOjE3MTg3MTk5MzMsImlzcyI6Imlzc3VlciIsImF1ZCI6ImF1ZGllbmNeIn0._gHMSxxCqJ3b5b7DZeRtWa41W5rzkI5OmXkRhkPJwDI

### SocialInteraction / groups
# @name /SocialInteraction/groups
POST {{baseUrl}}/SocialInteraction/groups
Authorization: {{apiKey}}
Content-Type: application/json
Accept: text/plain

{
  "groupName": "<string>",
  "description": "<string>"
}

<> ./StackUnderFlow API_responses/created.201.txt
<> ./StackUnderFlow API_responses/bad_request.400.json
<> ./StackUnderFlow API_responses/internal_server_error.500.txt

### User / register
# @name /User/register
POST {{baseUrl}}/User/register
Authorization: {{apiKey}}
Content-Type: application/json

{
  "email": "<email>",
  "password": "<string>",
  "userName": "<string>"
}

<> ./StackUnderFlow API_responses/ok.200.txt

### User / login
# @name /User/login
POST {{baseUrl}}/User/login
Authorization: {{apiKey}}
Content-Type: application/json
Accept: text/plain

{
  "email": "<email>",
  "password": "<string>"
}

<> ./StackUnderFlow API_responses/ok.200.txt
<> ./StackUnderFlow API_responses/not_found.404.json
<> ./StackUnderFlow API_responses/internal_server_error.500.txt
