### Environment Variables
@baseUrl =https://stackunderflowbackend.azurewebsites.net
@apiKey =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMSIsIm5iZiI6MTcxODc0ODQ1MSwiZXhwIjoxNzE4ODM0ODUxLCJpYXQiOjE3MTg3NDg0NTEsImlzcyI6Imlzc3VlciIsImF1ZCI6ImF1ZGllbmNlIn0.M6eqzjIwWo_l1CfMlHmOjqn2_s3DotGhfgD91-zL50Y

### S'abonner à un pipeline via WebSocket
@pipelineId =feda659f-6460-42d3-b65e-0e3d2aad6d3f
WEBSOCKET stackunderflowbackend.azurewebsites.net/Runner/subscribe/{{pipelineId}}